[package]
name = "aims_worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
aims_common = { path = "../../crates/common" }
aims_attendance_engine = { path = "../../crates/attendance_engine" }
