[package]
name = "aims_auth"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
argon2 = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
jsonwebtoken = "9"
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
aims_common = { path = "../common" }
