services:
  postgres:
    image: postgres:18
    container_name: aims-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: AIMS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@123

    ports:
      - "5432:5432"

    volumes:
      - aims_postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d AIMS"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  aims_postgres_data:
