# docker/Dockerfile.worker
FROM rust:1-slim as builder

WORKDIR /usr/src/aims

RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

ENV SQLX_OFFLINE=true

COPY Cargo.toml Cargo.lock ./
COPY apps ./apps
COPY crates ./crates
COPY .sqlx ./.sqlx

RUN cargo build --release --package aims_worker

FROM debian:bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/aims/target/release/aims_worker /app/aims-worker

ENTRYPOINT ["/app/aims-worker"]
