FROM rust:1.85-alpine as builder
WORKDIR /app
RUN apk add --no-libc-dev musl-dev gcc
COPY Cargo.toml ./
COPY crates ./crates
COPY apps ./apps
RUN cargo build --release -p aims_api

FROM alpine:3.21
WORKDIR /app
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /app/target/release/aims_api /app/aims_api
EXPOSE 8080
ENTRYPOINT ["/app/aims_api"]
