-- 001_extensions_and_types.sql
-- AIMS PostgreSQL 18.4 Custom ENUM Types

CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');
CREATE TYPE employee_status AS ENUM ('ACTIVE', 'PROBATION', 'SUSPENDED', 'RESIGNED', 'RETIRED');
CREATE TYPE import_batch_status AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL');
CREATE TYPE punch_type AS ENUM ('IN', 'OUT', 'UNKNOWN');
CREATE TYPE attendance_status AS ENUM (
    'PRESENT', 'LATE', 'ABSENT', 'HALF_DAY', 'EARLY_EXIT', 
    'LATE_AND_EARLY_EXIT', 'INCOMPLETE', 'HOLIDAY', 'WEEKLY_OFF', 
    'LEAVE', 'ON_DUTY', 'EXEMPTED', 'UNKNOWN'
);
CREATE TYPE correction_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');
