ALTER TABLE import_templates
    ADD COLUMN IF NOT EXISTS file_type VARCHAR(16) NOT NULL DEFAULT 'CSV',
    ADD COLUMN IF NOT EXISTS delimiter VARCHAR(8) NOT NULL DEFAULT ',',
    ADD COLUMN IF NOT EXISTS header_row_index INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS column_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS time_format VARCHAR(32) NOT NULL DEFAULT 'HH:mm:ss',
    ADD COLUMN IF NOT EXISTS interpretation_mode VARCHAR(32) NOT NULL DEFAULT 'EXPLICIT_DIRECTION';

ALTER TABLE import_templates
    ALTER COLUMN employee_code_column DROP NOT NULL,
    ALTER COLUMN punch_time_column DROP NOT NULL;
