use aims_common::Result;
use aims_domain::AttendanceDaily;
use chrono::NaiveDate;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportMetadata {
    pub report_title: String,
    pub organization_name: String,
    pub generated_at: String,
    pub generated_by: String,
    pub period_start: NaiveDate,
    pub period_end: NaiveDate,
}

pub struct ReportEngine;

impl ReportEngine {
    pub fn generate_summary_csv(
        metadata: &ReportMetadata,
        records: &[AttendanceDaily],
    ) -> Result<String> {
        let mut out = String::new();
        out.push_str(&format!("# Organization: {}\n", metadata.organization_name));
        out.push_str(&format!("# Report: {}\n", metadata.report_title));
        out.push_str(&format!("# Generated By: {}\n", metadata.generated_by));
        out.push_str("EmployeeID,SectionID,Date,FirstIN,LastOUT,DutyMinutes,ShiftStartDelay,LateAfterGrace,Status\n");

        for r in records {
            out.push_str(&format!(
                "{},{},{},{},{},{},{},{},{:?}\n",
                r.employee_id,
                r.section_id,
                r.attendance_date,
                r.first_in.map(|t| t.to_rfc3339()).unwrap_or_default(),
                r.last_out.map(|t| t.to_rfc3339()).unwrap_or_default(),
                r.total_duty_minutes,
                r.minutes_after_shift_start,
                r.late_after_grace_minutes,
                r.status
            ));
        }

        Ok(out)
    }
}
