[package]
name = "aims-api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
axum-extra.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
dotenvy = "0.15"
tower = "0.5"
tower-http = { version = "0.6", features = [
    "compression-full",
    "cors",
    "request-id",
    "timeout",
    "trace"
] }
http = "1"
aims_auth = { path = "../../crates/auth" }
aims_database = { path = "../../crates/database" }
aims_common = { path = "../../crates/common" }
aims_domain = { path = "../../crates/domain" }
time = { workspace = true }
